### Build a DNN using Keras with `RELU` and `ADAM`

#### Load tensorflow

In [0]:
%tensorflow_version 2.x

import tensorflow as tf 
print ('we are using tensorflow version',tf.__version__)

TensorFlow 2.x selected.
we are using tensorflow version 2.1.0


#### Collect Fashion mnist data from tf.keras.datasets 

In [0]:
(trainX, trainY),(testX, testY) = tf.keras.datasets.fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [0]:
print ('traing set shape',trainX.shape)
print ('training set shape',trainY.shape)
print ('test set shape',testX.shape)
print ('test set shape',testY.shape)

traing set shape (60000, 28, 28)
training set shape (60000,)
test set shape (10000, 28, 28)
test set shape (10000,)


#### Change train and test labels into one-hot vectors

In [0]:
#Convert labels to one hot encoding
train = tf.keras.utils.to_categorical(trainY, num_classes=10)
test = tf.keras.utils.to_categorical(testY, num_classes=10)

#### Build the Graph

#### Initialize model, reshape & normalize data

In [0]:
tf.keras.backend.clear_session()
#Initialize model, reshape & normalize data
model = tf.keras.models.Sequential()

#Reshape data from 2D (28,28) to 3D (28, 28, 1)
model.add(tf.keras.layers.Reshape((28,28,1),input_shape=(28,28,)))

#normalize data
model.add(tf.keras.layers.BatchNormalization())

#### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [0]:
#Add first convolutional layer
model.add(tf.keras.layers.Conv2D(32, #Number of filters 
                                 kernel_size=(3,3), #Size of the filter
                                 activation='relu'))

#Add second convolutional layer
model.add(tf.keras.layers.Conv2D(64, kernel_size=(3,3), activation='relu'))

#Add MaxPooling layer
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))

#Flatten the output
model.add(tf.keras.layers.Flatten())

#Dense layer
model.add(tf.keras.layers.Dense(200, activation='relu'))

model.add(tf.keras.layers.Dense(100, activation='relu'))

#Add another dropout layer
model.add(tf.keras.layers.Dropout(0.25))


### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [0]:
#Output layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))


model.compile(optimizer='adam', 
              loss='categorical_crossentropy', metrics=['accuracy'])

In [0]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 28, 28, 1)         0         
_________________________________________________________________
batch_normalization (BatchNo (None, 28, 28, 1)         4         
_________________________________________________________________
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 9216)              0         
_________________________________________________________________
dense (Dense)                (None, 200)               1

In [0]:
#Train the model
model.fit(trainX,train,          
          validation_data=(testX,test),
          epochs=10,
          batch_size=32)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 168s 3ms/sample - loss: 0.3771 - accuracy: 0.8667 - val_loss: 0.2627 - val_accuracy: 0.9044
Epoch 2/10
60000/60000 [==============================] - 166s 3ms/sample - loss: 0.2309 - accuracy: 0.9155 - val_loss: 0.2443 - val_accuracy: 0.9111
Epoch 3/10
60000/60000 [==============================] - 166s 3ms/sample - loss: 0.1731 - accuracy: 0.9360 - val_loss: 0.2445 - val_accuracy: 0.9157
Epoch 4/10
60000/60000 [==============================] - 167s 3ms/sample - loss: 0.1334 - accuracy: 0.9510 - val_loss: 0.2528 - val_accuracy: 0.9173
Epoch 5/10
60000/60000 [==============================] - 168s 3ms/sample - loss: 0.1033 - accuracy: 0.9618 - val_loss: 0.2672 - val_accuracy: 0.9192
Epoch 6/10
60000/60000 [==============================] - 167s 3ms/sample - loss: 0.0778 - accuracy: 0.9721 - val_loss: 0.3082 - val_accuracy: 0.9240
Epoch 7/10
60000/60000 [==========================

In [0]:
print ('Acuraccy on test set is found to be 92.30% on 10th itration ' )

Acuraccy on test set is found to be 92.30% on 10th itration 


In [0]:
print ('validation accuracy is 92.30%')

validation accuracy is 92.30%


In [0]:
from sklearn.metrics import classification_report,confusion_matrix
test1 = tf.cast(testX, tf.float32)
print(confusion_matrix(model.predict_classes(test1), testY))

[[851   1  11  20   1   0  73   0   3   0]
 [  0 980   1   2   0   0   0   0   0   0]
 [ 22   0 900  13  44   0  54   0   4   1]
 [ 18  12   6 940  36   0  23   1   6   0]
 [  2   1  26  10 845   0  37   0   1   0]
 [  2   0   0   0   0 984   0   9   1   3]
 [ 99   5  56  13  74   0 807   0   2   0]
 [  0   0   0   0   0  10   0 979   2  33]
 [  6   1   0   0   0   1   6   0 981   0]
 [  0   0   0   2   0   5   0  11   0 963]]


In [0]:
from sklearn.metrics import classification_report,confusion_matrix

print("Please find the classification report as following: \n")
print(classification_report(model.predict_classes(test1),testY))

Please find the classification report as following: 

              precision    recall  f1-score   support

           0       0.85      0.89      0.87       960
           1       0.98      1.00      0.99       983
           2       0.90      0.87      0.88      1038
           3       0.94      0.90      0.92      1042
           4       0.84      0.92      0.88       922
           5       0.98      0.98      0.98       999
           6       0.81      0.76      0.79      1056
           7       0.98      0.96      0.97      1024
           8       0.98      0.99      0.98       995
           9       0.96      0.98      0.97       981

    accuracy                           0.92     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.92      0.92      0.92     10000

